export const SHOPS_LIST_LOAD_START = 'SHOPS_LIST_LOAD_START';
export const SHOPS_LIST_LOAD_SUCCESS = 'SHOPS_LIST_LOAD_SUCCESS';
export const SHOPS_LIST_LOAD_FAIL = 'SHOPS_LIST_LOAD_FAIL';

export const SHOP_LOAD_START = 'SHOP_LOAD_START';
export const SHOP_LOAD_SUCCESS = 'SHOP_LOAD_SUCCESS';
export const SHOP_LOAD_FAIL = 'SHOP_LOAD_FAIL';
export const SHOP_STATISTICS_LOAD_START = 'SHOP_STATISTICS_LOAD_START';
export const SHOP_STATISTICS_LOAD_SUCCESS = 'SHOP_STATISTICS_LOAD_SUCCESS';
export const SHOP_STATISTICS_LOAD_FAIL = 'SHOP_STATISTICS_LOAD_FAIL';
export const SHOP_CHANGE_NAME = 'SHOP_CHANGE_NAME';
export const SHOP_CHANGE_GROUP_VALUE = 'SHOP_CHANGE_GROUP_VALUE';
export const SHOP_CHANGE_PROVIDERS = 'SHOP_CHANGE_PROVIDERS';
export const SHOP_GROUPS_UPDATE = 'SHOP_GROUPS_UPDATE';
export const SHOP_CREATE_START = 'SHOP_CREATE_START';
export const SHOP_CREATE_SUCCESS = 'SHOP_CREATE_SUCCESS';
export const SHOP_CREATE_FAIL = 'SHOP_CREATE_FAIL';
export const SHOP_UPDATE_START = 'SHOP_UPDATE_START';
export const SHOP_UPDATE_SUCCESS = 'SHOP_UPDATE_SUCCESS';
export const SHOP_UPDATE_FAIL = 'SHOP_UPDATE_FAIL';
export const SHOP_DELETE_START = 'SHOP_DELETE_START';
export const SHOP_DELETE_SUCCESS = 'SHOP_DELETE_SUCCESS';
export const SHOP_DELETE_FAIL = 'SHOP_DELETE_FAIL';
export const SHOP_SAVE_PRICE_START = 'SHOP_SAVE_PRICE_START';
export const SHOP_SAVE_PRICE_SUCCESS = 'SHOP_SAVE_PRICE_SUCCESS';
export const SHOP_SAVE_PRICE_FAIL = 'SHOP_SAVE_PRICE_FAIL';
export const SHOP_CLEAR_STATE = 'SHOP_CLEAR_STATE';

