export const SEARCHING_START = 'SEARCHING_START';
export const SEARCHING_SUCCESS = 'SEARCHING_SUCCESS';
export const SEARCHING_FAIL = 'SEARCHING_FAIL';
export const SEARCHING_CAPTCHA = 'SEARCHING_CAPTCHA';
export const SEARCHING_SETTINGS_CHANGE = 'SEARCHING_SETTINGS_CHANGE';
export const SEARCHING_CLEAR_STATE = 'SEARCHING_CLEAR_STATE';

export const GET_SEARCHING_PRODUCT_DATA_START = 'GET_SEARCHING_PRODUCT_DATA_START';
export const GET_SEARCHING_PRODUCT_DATA_SUCCESS = 'GET_SEARCHING_PRODUCT_DATA_SUCCESS';
export const GET_SEARCHING_PRODUCT_DATA_FAIL = 'GET_SEARCHING_PRODUCT_DATA_FAIL';
export const PARSING_SET_PRODUCT_PART = 'PARSING_SET_PRODUCT_PART';
export const PARSING_SAVE_RESULT_PRODUCT_START = 'PARSING_SAVE_RESULT_PRODUCT_START';
export const PARSING_SAVE_RESULT_PRODUCT_SUCCESS = 'PARSING_SAVE_RESULT_PRODUCT_SUCCESS';
export const PARSING_SAVE_RESULT_PRODUCT_FAIL = 'PARSING_SAVE_RESULT_PRODUCT_FAIL';
export const PARSING_PRODUCTS_DONE = 'PARSING_PRODUCTS_DONE';
