export const PROVIDERS_LIST_LOAD_START = 'PROVIDERS_LIST_LOAD_START';
export const PROVIDERS_LIST_LOAD_SUCCESS = 'PROVIDERS_LIST_LOAD_SUCCESS';
export const PROVIDERS_LIST_LOAD_FAIL = 'PROVIDERS_LIST_LOAD_FAIL';

export const PROVIDER_GET_DATA_START = 'PROVIDER_GET_DATA_START';
export const PROVIDER_GET_DATA_SUCCESS = 'PROVIDER_GET_DATA_SUCCESS';
export const PROVIDER_GET_DATA_FAIL = 'PROVIDER_GET_DATA_FAIL';
export const PROVIDER_DATA_CHANGE = 'PROVIDER_DATA_CHANGE';
export const PROVIDER_PRICE_RANGE_CHANGE = 'PROVIDER_PRICE_RANGE_CHANGE';
export const PROVIDER_PRICE_RANGE_ADD = 'PROVIDER_PRICE_RANGE_ADD';
export const PROVIDER_PRICE_RANGE_DELETE = 'PROVIDER_PRICE_RANGE_DELETE';
export const PROVIDER_SETTINGS_CHANGE = 'PROVIDER_SETTINGS_CHANGE';
export const PROVIDER_VALIDATION_HANDLER = 'PROVIDER_VALIDATION_HANDLER';
export const PROVIDER_PRICE_FILE_PARSE_START = 'PROVIDER_PRICE_FILE_PARSE_START';
export const PROVIDER_PRICE_FILE_PARSE_SUCCESS = 'PROVIDER_PRICE_FILE_PARSE_SUCCESS';
export const PROVIDER_PRICE_FILE_PARSE_FAIL = 'PROVIDER_PRICE_FILE_PARSE_FAIL';
export const PROVIDER_CREATE_START = 'PROVIDER_CREATE_START';
export const PROVIDER_CREATE_SUCCESS = 'PROVIDER_CREATE_SUCCESS';
export const PROVIDER_CREATE_FAIL = 'PROVIDER_CREATE_FAIL';
export const PROVIDER_UPDATE_PRODUCTS_START = 'PROVIDER_UPDATE_PRODUCTS_START';
export const PROVIDER_UPDATE_PRODUCTS_SUCCESS = 'PROVIDER_UPDATE_PRODUCTS_SUCCESS';
export const PROVIDER_UPDATE_PRODUCTS_FAIL = 'PROVIDER_UPDATE_PRODUCTS_FAIL';
export const PROVIDER_UPDATE_START = 'PROVIDER_UPDATE_START';
export const PROVIDER_UPDATE_SUCCESS = 'PROVIDER_UPDATE_SUCCESS';
export const PROVIDER_UPDATE_FAIL = 'PROVIDER_UPDATE_FAIL';
export const PROVIDER_DELETE_START = 'PROVIDER_DELETE_START';
export const PROVIDER_DELETE_SUCCESS = 'PROVIDER_DELETE_SUCCESS';
export const PROVIDER_DELETE_FAIL = 'PROVIDER_DELETE_FAIL';
export const PROVIDER_STATISTICS_LOAD_START = 'PROVIDER_STATISTICS_LOAD_START';
export const PROVIDER_STATISTICS_LOAD_SUCCESS = 'PROVIDER_STATISTICS_LOAD_SUCCESS';
export const PROVIDER_STATISTICS_LOAD_FAIL = 'PROVIDER_STATISTICS_LOAD_FAIL';
export const PROVIDER_CONFIRM_ERROR = 'PROVIDER_CONFIRM_ERROR';
export const PROVIDER_CLEAR_DATA = 'PROVIDER_CLEAR_DATA';




