export const PRODUCTS_LIST_LOAD_START = 'PRODUCTS_LIST_LOAD_START';
export const PRODUCTS_LIST_LOAD_SUCCESS = 'PRODUCTS_LIST_LOAD_SUCCESS';
export const PRODUCTS_LIST_LOAD_FAIL = 'PRODUCTS_LIST_LOAD_FAIL';
export const PRODUCTS_LIST_CONFIRM_ERROR = 'PRODUCTS_LIST_CONFIRM_ERROR';
export const PRODUCTS_LIST_CLEAR = 'PRODUCTS_LIST_CLEAR';
